---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/bkahlert/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/com.bkahlert/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .osx
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - bat
  - git
  - gpg
  - gradle
  - helm
  - jq
  - maven
  - mcrypt
  - node
  - openjdk
  - openssl
  - ssh-copy-id
  - sshfs
  - sshpass
  - xz
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - balenaetcher
  - browserosaurus
  - caffeine
  - colorsnapper
  - clickup
  - daisydisk
  - docker
  - dropbox
  - firefox
  - iterm2
  - chromedriver
  - google-chrome
  - freesmug-chromium
  - microsoft-edge
  - handbrake
  - sequel-ace
  - slack
  - sublime-text
  - transmit
  - virtualbox
  - virtualbox-extension-pack
  - vagrant
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 1482490089 # Tampermonkey
  - 1444383602 # Goodnotes 5
  - 403304796 # iNet Network Scanner
  - 587512244 # Kaleidoscope

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
