---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/dock/README.md
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - App Store
  - Reminders
  - Notes
  - Photos
dockitems_persist:
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 2
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 3
  - name: Firefox Developer Edition
    path: "/Applications/Firefox Developer Edition.app"
    pos: 4
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 5
  - name: Microsoft Edge
    path: "/Applications/Microsoft Edge.app"
    pos: 6
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 7
  - name: Mail
    path: "/System/Applications/Mail.app"
    pos: 8
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 9
  - name: Unibox
    path: "/Applications/Unibox.app"
    pos: 10
  - name: Microsoft Outlook
    path: "/Applications/Microsoft Outlook.app"
    pos: 11
  - name: Microsoft Teams
    path: "/Applications/Microsoft Teams.app"
    pos: 12
  - name: Contacts
    path: "/System/Applications/Contacts.app"
    pos: 13
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 14
  - name: Messages
    path: "/System/Applications/Messages.app"
    pos: 15
  - name: ChatMate for WhatsApp
    path: "/Applications/ChatMate for WhatsApp.app"
    pos: 16
  - name: Music
    path: "/System/Applications/Music.app"
    pos: 17
  - name: System Preferences
    path: "/System/Applications/System Preferences.app"
    pos: 18
  - name: Ferdi
    path: "/Applications/Ferdi.app"
    pos: 19
  - name: Adobe Illustrator 2021
    path: "/Applications/Adobe Illustrator 2021/Adobe Illustrator 2021.app"
    pos: 20
  - name: Adobe Photoshop 2021
    path: "/Applications/Adobe Photoshop 2021/Adobe Photoshop 2021.app"
    pos: 21
  - name: GitHub Desktop
    path: "/Applications/GitHub Desktop.app"
    pos: 22
  - name: Fork
    path: "/Applications/Fork.app"
    pos: 23
  - name: Coda 2
    path: "/Applications/Coda 2.app"
    pos: 24
  - name: Terminal
    path: "/Applications/Terminal.app"
    pos: 25
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 26
  - name: IntelliJ IDEA
    path: "/Users/bkahlert/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/212.5080.55"
    pos: 27
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 28
  - name: Xcode
    path: "/Applications/Xcode.app"
    pos: 29
  - name: Paw
    path: "/Applications/SetApp/Paw.app"
    pos: 30
  - name: Postman
    path: "/Applications/Postman.app"
    pos: 31
  - name: Transmit
    path: "/Applications/Transmit.app"
    pos: 32


configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/bkahlert/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/com.bkahlert/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bashrc
  - .oh-my-zsh
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .iterm2_shell_integration.zsh
  - .osx
  - .p10k.zsh
  - .tmux.conf
  - .whalebrew
  - .zshrc

# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/README.md
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - boz/repo
  - johanhaleby/kubetail/kubetail

#homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - autoconf
  - antigen
  - bat
  - git
  - gpg
  - gradle
  - helm
  - jq
  - boz/repo/kail # tail for Kubernetes pod logs
  - krew # Homebrew for kubectl; e.g. kubectl krew install ingress-nginx
  - kubectx # kubectl context switcher + kubens — kubectl namespace switcher
  - johanhaleby/kubetail # tail for logs of multiple Kubernetes pods
  - maven
  - mcrypt
  - node
  - python
  - openjdk
  - openssl
  - optipng
  - ssh-copy-id
  - sshfs
  - sshpass
  - tldr # type "tldr x" instead of "man x" for examples for a command
  - tmux
  - whalebrew # Homebrew for Docker
  - wget
  - xz
  - zsh-syntax-highlighting

#homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  #  - adobe-creative-cloud
  - balenaetcher
  - browserosaurus
  - caffeine
  - chatmate-for-whatsapp
  - colorsnapper
  - clickup
  - daisydisk
  - docker
  - dropbox
  - firefox
  - firefox-developer-edition
  - imageoptim
  - iterm2
  - lastpass
  - lens # Kubernetes IDE
  - google-chrome
  - microsoft-edge
  - moom
  - handbrake
  - osxfuse # needed for sshfs
  - postman
  - sequel-ace
  - slack
  - transmit
  - vagrant
  - vagrant-manager
  - virtualbox
  #  - virtualbox-extension-pack
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/mas/README.md
mas_installed_apps:
  - {id: 1482490089, name: "Tampermonkey"}
  - {id: 1444383602, name: "GoodNotes 5"}
  - {id: 403304796, name: "iNet Network Scanner"}
  - {id: 587512244, name: "Kaleidoscope"}

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
