#!/usr/bin/env bash
set -o nounset
set -o pipefail
#set -o xtrace

eval "$(curl -sLS https://github.com/bkahlert/-/raw/main/semantics.sh)"

yes=0
while test $# != 0
do
    case "$1" in
    -y) yes=1 ;;
    --yes) yes=1 ;;
    --) shift; break;;
    *)  usage ;;
    esac
    shift
done
[[ $yes -eq 1 ]] || prompt_continue "Setting up this Mac for development"
cd "${DIR}" || exit 1

sudo_forever

echo_start "Installing Xcode Command Line Tools"
sudo xcode-select --install &>/dev/null || true
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer >/dev/null
sudo chmod +x scripts/accept_xcode_license
sudo scripts/accept_xcode_license >/dev/null
echo_success

echo_start "Testing for Homebrew"
which brew &>/dev/null || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; brew update
echo_success

echo_start "Testing for Python3"
which pip3 &>/dev/null || brew install python
echo_success

echo_start "Testing for Ansible"
which ansible &>/dev/null || pip3 install ansible
echo_success

echo_start "Installing Ansible requirements"
ansible-galaxy install -r requirements.yml
echo_success

echo_start "Executing Ansible playbook"
ansible-playbook main.yml
echo_success
