#!/bin/sh
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py --user
python -m pip install --user ansible
python -m pip install --user paramiko
pip install argcomplete
activate-global-python-argcomplete
python -m pip install argcomplete
