#!/bin/sh
brew install bat # A cat(1) clone with syntax highlighting and Git integration.
# alias cat="bat --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
