#!/bin/sh
PWD_BACKUP=$PWD
KEY_BINDINGS_SOURCE_DIR="$PWD/KeyBindings"
KEY_BINDINGS_DEST_DIR="$HOME/Library/KeyBindings"
set -x
cd "${KEY_BINDINGS_SOURCE_DIR}" || exit
mkdir -p "${KEY_BINDINGS_DEST_DIR}" && cp ./*.* "${KEY_BINDINGS_DEST_DIR}"
cd "${PWD_BACKUP}" || exit
{ set +x; } 2>/dev/null
